title: "Workshop: IA Interpretable en Neurooncología"
description: "Decodificando la severidad tumoral mediante resonancia multimodal"
remote_theme: "mmistakes/minimal-mistakes"

baseurl: "/workshop_glioma_web"
url: "https://pamelaFranco.github.io"

author:
  name: "Dra. Pamela Franco"
  avatar: "/images/profile.png"
  bio: "IA e Interpretabilidad en Neurooncología"
  location: "Santiago, Chile"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:neurooncologia.ia@gmail.com"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/neuro_artint"

# Menú superior mapeado de forma nativa
site_navigation: main

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      mathjax: true